sudo: required

dist: trusty

language: java

group: edge

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - BASE_DIR=components
    - DEMO_DIR=demo
    - HADEMO_DIR=ha-demo

before_install:
  - docker -v
  - docker-compose -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker-compose -f $BASE_DIR/docker-compose.yml build && docker-compose -f $DEMO_DIR/docker-compose.yml build && docker-compose -f $DEMO_DIR/docker-compose.yml build && docker-compose -f $BASE_DIR/docker-compose.yml push && docker-compose -f $DEMO_DIR/docker-compose.yml push && docker-compose -f $HADEMO_DIR/docker-compose.yml push

