sudo: required

dist: trusty

language: java

group: edge

services:
  - docker

branches:
  only:
    - master

env:
  - BASE_DIR=components
  - BASE_DIR=demo
  - BASE_DIR=ha-demo

before_install:
  - docker -v
  - docker-compose -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: docker-compose -f $BASE_DIR/docker-compose.yml build && docker-compose -f $BASE_DIR/docker-compose.yml push

