version: '2'

services:

  keycloak:
      build: ./components/keycloak
      image: cyclonefp/keycloak
      #command: -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/keycloak/exports/keycloak-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
      restart: unless-stopped
      volumes:
        - ./data/keycloak/exports:/opt/keycloak/exports
      links:
        - keycloakdb
      expose:
        - "8080"
      ports:
        - "9080:8080"

  keycloakdb:
      image: mongo:3
      restart: unless-stopped
      volumes:
        - ./data/keycloak/db:/data/db
      expose:
        - "27017"

  samlbridge:
      build: ./components/samlbridge
      image: cyclonefp/samlbridge
      restart: unless-stopped
      #environment:
      #  - SSP_BASEURL=samlbridge/
      #  - SSP_PASSWORD=admin
      #  - SSP_SALT=defaultsalt
      #  - SSP_CONTACTNAME=
      #  - SSP_CONTACTEMAIL=
      expose:
        - "80"
      ports:
        - "8080:80"

  cacheclean:
      build: ./components/cache-clean
      image: cyclonefp/cacheclean
      restart: unless-stopped
      environment:
        - KEYCLOAK_ADMIN_USER=admin
        - KEYCLOAK_ADMIN_PASS=admin
        - KEYCLOAK_ADMIN_CLIENT=admin-cli
        - KEYCLOAK_REALM=master
        - PERIOD=60000
        - EXCLUDED_USERS=admin;owner;user;tub;uva;cnrs;guest
      links:
        - keycloakdb
        - keycloak

  cron:
      build: ./components/cron
      image: cyclonefp/cron
      restart: unless-stopped
      links:
        - samlbridge
