version: '2'

# Base Compose File for the Cyclone Federation Provider

services:

  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml
    ports:
        - "80:80"

  keycloak:
    build: ./components/keycloak
    image: cycloneproject/keycloak-postgres-base
    restart: unless-stopped
    command: -b 0.0.0.0
    environment:
      - KEYCLOAK_REALM
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT_5432_TCP_ADDR
      - POSTGRES_PORT_5432_TCP_PORT
    labels:
      - "traefik.enable=true"
      - "traefik.backend=keycloak"
      - "traefik.frontend.rule=PathPrefix:/,/auth"
    depends_on:
      - postgres
    expose:
      - "8080"

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./data/keycloak/db:/var/lib/postgresql/data
    expose:
      - "5432"

  samlbridge:
    build: ./components/samlbridge
    image: cycloneproject/samlbridge-base
    restart: unless-stopped
    environment:
      - FP_BASEURL
      - SAMLBRIDGE_CRON
      - SAMLBRIDGE_PASSWORD
      - SAMLBRIDGE_SALT
      - SAMLBRIDGE_CONTACTGIVENNAME
      - SAMLBRIDGE_CONTACTSURNAME
      - SAMLBRIDGE_CONTACTEMAIL
      - SAMLBRIDGE_ORGURL
      - SAMLBRIDGE_ORGDISPLAYNAME
      - SAMLBRIDGE_ORGNAME
      - POSTGRES_PORT_5432_TCP_ADDR
      - POSTGRES_PORT_5432_TCP_PORT
    labels:
      - "traefik.enable=true"
      - "traefik.backend=samlbridge"
      - "traefik.frontend.rule=PathPrefix:/samlbridge"
    volumes:
      - ./components/samlbridge/samlbridge-cert:/run/secrets
    expose:
      - "80"

  cron:
    build: ./components/cron
    image: cycloneproject/cron
    restart: unless-stopped
    environment:
      - SAMLBRIDGE_CRON
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - EXCLUDED_USERS
    depends_on:
      - keycloak
      - samlbridge

