version: '2'

services:

  keycloak:
    expose:
      - "8080"
    ports:
      - "9080:8080"

  samlbridge:
    expose:
      - "80"
    ports:
      - "8080:80"

  cron:
    volumes:
      - ./components/cron/periodic:/etc/periodic
