version: '2'

# Base Compose File for the Cyclone Federation Provider

services:

  keycloak:
      build: ./components/keycloak
      restart: unless-stopped
      links:
        - keycloakdb

  keycloakdb:
      image: postgres:alpine
      restart: unless-stopped
      expose:
        - "5432"

  samlbridge:
      build: ./components/samlbridge
      restart: unless-stopped

  cron:
      build: ./components/cron
      restart: unless-stopped
      links:
        - samlbridge
